#!/bin/bash
# $1 = Project Name

# Get variables
USER=$(git config --global user.name)
PROJECT=$1

# Create and enter git directory
mkdir $PROJECT 
cd $PROJECT

# Create beginning files
# README
touch README
echo "This is the README for $PROJECT" >> README

# .gitignore
touch .gitignore
echo "main
*.swp
*.swo
*.o" >> .gitignore

# Makefile
touch Makefile
echo "CC = g++
CFLAGS = -Wall
LDFLAGS = 
OBJFILES = 
TARGET = main

all: \$(TARGET)

\$(TARGET): \$(OBJFILES)
	\$(CC) \$(CFLAGS) -o \$(TARGET) \$(OBJFILES) \$(LDFLAGS)

clean:
	rm -f \$(OBJFILES) \$(TARGET) *~" >> Makefile

# Create Objects
PWD=`pwd`
COUNT=0
for object in "$@"; do
	if [ $COUNT -ne 0 ]; then
		object_maker $object
	else	
		# Skip first item (project name)
		let COUNT=COUNT+1
	fi
done

#	main
touch main.cc
echo "#include <iostream>

int main(int argc, char* argv[]) {
	return 0;
}" >> main.cc

sed -i "/^OBJFILES/ s/$/main.o /" Makefile

# Make first commit
git init
git add .
git commit -m "First commit of $PROJECT"
#git remote add origin https://github.com/$USER/$PROJECT.git
