#!/bin/bash
# $1 = Project Name

# Get variables
USER=$(git config --global user.name)
PROJECT=$1

# Create and enter git directory
mkdir $PROJECT 
cd $PROJECT

# Create beginning files
# README
touch README
echo "This is the README for $PROJECT" >> README

# .gitignore
touch .gitignore
echo "main
*.swp
*.swo
*.o" >> .gitignore

# Makefile
touch Makefile
echo "CC = g++
CFLAGS = -Wall
LDFLAGS = 
OBJFILES = 
TARGET = main

all: \$(TARGET)

\$(TARGET): \$(OBJFILES)
	\$(CC) \$(CFLAGS) -o \$(TARGET) \$(OBJFILES) \$(LDFLAGS)

clean:
	rm -f \$(OBJFILES) \$(TARGET) *~" >> Makefile

# Create object files
COUNT=0
for item in "$@"; do
	if [ $COUNT -ne 0 ]; then
		# Header
		touch $item.h
		echo "#ifndef $item.H
#define $item.H

class $item {
	public:
		$item();
		~$item();

	private:
};

#endif" >> $item.h

		# Source
		touch $item.cc
		echo "#include \"$item.h\"
$item::$item() {
}

$item::~$item() {
}" >> $item.cc

		#	Add object to makefile
		sed -i "/^OBJFILES/ s/$/$item.o /" Makefile

		# Increase Count
		let COUNT=COUNT+1
	else	
		# Skip first item (project name)
		let COUNT=COUNT+1
	fi
done

#	main
touch main.cc
echo "#include <iostream>

int main(int argc, char* argv[]) {
	return 0;
}" >> main.cc

sed -i "/^OBJFILES/ s/$/main.o /" Makefile

# Make first commit
git init
echo "Project initialized..."
vim README
echo "README updated..."
git add .
git commit -m "First commit of $PROJECT: Check README"
git branch -m master develop
echo "develop branch created (HEAD)..."
git branch release
echo "release branch created..."
echo "First commit is set. Ready to push the develop branch..."
echo "Go to https://github.com/new and make a new repo with the project name: $PROJECT"
read -p "Press enter once done"
git remote add origin https://github.com/$USER/$PROJECT.git
git push origin develop
echo "Develop branch successfuly pushed. Release branch is ready for merge when a releaseable version of develop is ready! Happy Building!!"
